baseURL = "https://clemvst.github.io/"
languageCode = "en-us"
title = "Clemence Vast"
theme = "hugo-resume"

[params]
    firstName = "Clemence"
    lastName = "Vast"
    address = "Paris, France"
    phone = ""
    contactNote = "Computer science engineer"
    profileImage = "images/clemence.jpg"
    email = "clemence.vast@mines-nancy.org"
    description = "Deep learning and Computer science engineering student. Looking for an internship in Data or AI from Spring 2020."
    favicon = ""
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/clemence-vast/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/clemvst/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/11856794"
    icon = "stack-overflow"

